#!/bin/bash -ea

target=${1-dev}
echo "building ui modules with target=$target"

nodever="$(node --version)"
echo "node: $nodever"
echo "pnpm: $(pnpm --version)"

[[ "$nodever" =~ ^v1[2-6]\.[0-9]+\.[0-9]+$ ]] || { echo "Node version >=12 and <=16 required. Found: $nodever"; exit 1; }

cd "$(git rev-parse --show-toplevel)"

mkdir -p public/compiled

pnpm install
pnpm recursive run --workspace-concurrency 0 "$target"

build_plugin() {
  echo
  echo "### ui/$1 plugin $2 ###"
  set -ev
  cd ui/$1
  pnpm run plugin-$target $2
}

site_plugins="tvEmbed puzzleEmbed analyseEmbed user modUser clas coordinate captcha expandText team forum account coachShow coachForm challengePage checkout plan login passwordComplexity tourForm teamBattleForm gameSearch userComplete infiniteScroll flatpickr teamAdmin appeal modGames publicChats contact userGamesDownload modActivity"
round_plugins="nvui keyboardMove"
analyse_plugins="nvui studyTopicForm"
puzzle_plugins="nvui dashboard"

if type -p parallel; then # parallel execution!
  if [ -z "$P_OPTS" -a ! -e ~/.parallel/config ]; then
    P_OPTS="-j+0 --halt 2"
    [ -n "$GITHUB_WORKFLOW" ] || P_OPTS+=" --bar"
  fi
  set -x
  parallel --gnu $P_OPTS build_plugin site ::: $site_plugins
  parallel --gnu $P_OPTS build_plugin round ::: $round_plugins
  parallel --gnu $P_OPTS build_plugin analyse ::: $analyse_plugins
  parallel --gnu $P_OPTS build_plugin puzzle ::: $puzzle_plugins
else # sequential execution
  echo "For faster builds, install GNU parallel."
  for plugin in $site_plugins; do (build_plugin site $plugin); done
  for plugin in $round_plugins; do (build_plugin round $plugin); done
  for plugin in $analyse_plugins; do (build_plugin analyse $plugin); done
  for plugin in $puzzle_plugins; do (build_plugin puzzle $plugin); done
fi
